---
- name: add distribution-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

#- name: install iptables
#  emerge: name=net-firewall/iptables state=present
#  tags: packages

- include: debian.yml
  when: ansible_os_family == 'Debian'

- include: gentoo.yml
  when: ansible_os_family == 'Gentoo'
